version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_bookclub
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - D:/workspace/docker/postgres_bookclub:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis_bookclub
    hostname: redis_bookclub
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    volumes:
      - D:/workspace/docker/redis_bookclub/data:/data
    restart: always
volumes:
  db:
    driver: local